default: &default
  adapter: postgresql
  username: postgres
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  database: rails_practice_api_development

test:
  <<: *default
  username: postgres
  database: rails_practice_api_test

production:
  <<: *default
  database: rails_practice_api_production
  username: rails_practice_api
  password: <%= ENV['RAILS_PRACTICE_API_DATABASE_PASSWORD'] %>
